### PR TITLE
Fixed Overwatch Patch Notes

### PR DESCRIPTION
**Pull request by jluthi**
Fixed longstanding issue of patch-notes being out of date. App now looks at the official playoverwatch.com patch notes web page.

### CODE REVIEW

**Review by jluthi — COMMENTED** [review]
PatchNotesFragment.java  is the only file that needs to be merged for App fix.

**Comment by leotianlizhan** [comment]
@joell29 could you remove the `.idea` folder?

**Comment by joell29** [comment]
Done!

**Review by leotianlizhan — APPROVED** [review]

**Comment by joell29** [comment]
When will this get merged & updated? The app patch-notes is basically borked as it stands.

**Pull request merged**
